### ISSUE TITLE
Crash à l'ajout d'un mod

### ISSUE THREAD

**Issue by moriceh** [FFMT/ModPackInstaller#15]
Bonjour,
Je me sers du ModPackInstaller mais quand j'ajoute un mod (dans le ftp), j'ai cette erreur : 
`Successfully read file : sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@4517d9a3
Successfully read file : sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream@28a418fc
Starting updater !
java.net.UnknownHostException: ...
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at fr.minecraftforgefrance.common.RemoteInfoReader.getWhileList(RemoteInfoReader.java:118)
	at fr.minecraftforgefrance.common.FileChecker.compare(FileChecker.java:86)
	at fr.minecraftforgefrance.common.FileChecker.<init>(FileChecker.java:38)
	at fr.minecraftforgefrance.updater.Updater.<init>(Updater.java:91)
	at fr.minecraftforgefrance.updater.Updater.main(Updater.java:36)
Exception in thread "main" java.lang.NullPointerException
	at fr.minecraftforgefrance.common.FileChecker.compare(FileChecker.java:86)
	at fr.minecraftforgefrance.common.FileChecker.<init>(FileChecker.java:38)
	at fr.minecraftforgefrance.updater.Updater.<init>(Updater.java:91)
	at fr.minecraftforgefrance.updater.Updater.main(Updater.java:36)
`
Et je suis obligé de réinstaller le ModPackInstaller pour que ça refonctionne...
Pouvez-vous m'aider ?

**Comment by robin4002** [comment]
Salut,
Je peux avoir un lien vers le fichier remote_profile.json ? Il semblerait que la whitelist soit invalide.

**Comment by moriceh** [comment]
C'est bon ça marche, j'ai supprimé la ligne whitelist et je n'ai plus de crash ! Merci de l'info !
